// src/app/layout.js

import { Inter } from 'next/font/google'
import './globals.css'
import { StrictMode } from 'react'
import { EmailStatusProvider } from './contexts/EmailStatusContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <EmailStatusProvider>
      <html lang="en">
        <title>Liberty Notes AI</title>
        <body className={inter.className}>{children}</body>
      </html>
    </EmailStatusProvider>
  )
}
